---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/img"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
