---
name: Docker

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: img
        run: docker build . --pull
      - name: Test the Docker image
        working-directory: img
        run: docker compose -f docker-compose.test.yml run sut
